# Generated by Django 4.2.11 on 2024-03-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_gamereview_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
