# Generated by Django 4.2.11 on 2024-03-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_gamereview_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
