# Generated by Django 4.2.11 on 2024-03-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_gamereview_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='description',
            field=models.CharField(max_length=550),
        ),
    ]
